language: node_js

node_js:
    - 10

notifications:
    email:
        recipients:
            - adrian@waavi.com
            - alejandro@waavi.com
        on_success: never
        on_failure: always
